/* Aroa & Jon — Cartera de inmuebles · Fuente única de datos
   Para añadir/editar una propiedad, modifica este array.
   La landing y la página /cartera se actualizan solas. */

window.AJ_PROPERTIES = [
  {
    id: "higer-golf",
    titulo: "Villa Higer Golf - Hondarribia",
    tipo: "Villa",
    zona: "Hondarribia",
    direccion: "Camino Higer, Hondarribia",
    precio: "3.900.000 €",
    m2: "625 m²",
    habitaciones: 7,
    banos: 5,
    parcela: "1.760 m²",
    extras: ["Piscina climatizada", "Ascensor privado", "Garaje", "Vistas al mar"],
    descripcionCorta: "Villa exclusiva junto al faro de Higuer. Privacidad absoluta, piscina climatizada y vistas al mar Cantábrico y la bahía de Txingudi.",
    fotos: [
      "../../assets/higer-golf-1.png",
      "../../assets/higer-golf-2.png",
      "../../assets/higer-golf-3.png",
      "../../assets/higer-golf-4.png",
    ],
    idealista: "https://www.idealista.com/inmueble/108478494/",
    destacado: true,
  },
  {
    id: "foru-kalea",
    titulo: "Villa Alkiza - Hondarribia",
    tipo: "Chalet",
    zona: "Hondarribia",
    direccion: "Calle Foru, 2, Hondarribia",
    precio: "2.690.000 €",
    m2: "450 m²",
    habitaciones: 6,
    banos: 5,
    parcela: "834 m²",
    extras: ["Primera línea", "Vistas al mar", "Terraza", "Txoko"],
    descripcionCorta: "Villa única del año 1970 en primera línea de Hondarribia. Seis habitaciones, jardín, txoko y vistas despejadas al mar desde el centro del pueblo.",
    fotos: [
      "../../assets/foru-kalea-1.png",
      "../../assets/foru-kalea-2.png",
      "../../assets/foru-kalea-3.png",
    ],
    idealista: "https://www.idealista.com/inmueble/108061406/",
    destacado: true,
  },
  {
    id: "villa-birdie",
    titulo: "Villa Birdie - Donosti",
    tipo: "Villa",
    zona: "Donostia",
    direccion: "Intxaurrondo, Donostia-San Sebastián",
    precio: "2.620.000 €",
    m2: "443 m²",
    habitaciones: 9,
    banos: 9,
    parcela: "685 m²",
    extras: ["Piscina", "Jardín", "Parking 6 vehículos", "Ascensor"],
    descripcionCorta: "Exclusiva villa en Ategorrieta operando como hotel boutique de alto nivel. Rehabilitada en 2017, a 5 minutos en bici de la playa de Gros.",
    fotos: [
      "../../assets/villa-birdie-1.png",
      "../../assets/villa-birdie-2.png",
      "../../assets/villa-birdie-3.png",
      "../../assets/villa-birdie-4.png",
    ],
    idealista: "https://www.idealista.com/inmueble/111250842/",
    destacado: false,
  },
  {
    id: "gaztaiondo",
    titulo: "Piso Gaztainondo Kalea - Irun",
    tipo: "Piso",
    zona: "Irun",
    direccion: "Calle Gaztainondo, 5, Irun",
    precio: "299.000 €",
    m2: "77 m²",
    habitaciones: 2,
    banos: 2,
    parcela: null,
    extras: ["Exterior", "Mucha luz", "Esquina", "Cerca del tren"],
    descripcionCorta: "Piso en esquina con dos fachadas y luz natural todo el día. Edificio recién reformado, acceso privado para 4 vecinos. A dos pasos de la estación.",
    fotos: [
      "../../assets/gaztaiondo-1.png",
      "../../assets/gaztaiondo-2.png",
      "../../assets/gaztaiondo-3.png",
      "../../assets/gaztaiondo-4.png",
    ],
    idealista: "https://www.idealista.com/inmueble/111597970/",
    destacado: false,
  },
];
